name: Template CI/CD

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: {}

concurrency:
  group: deploy-universal
  cancel-in-progress: true

permissions:
  contents: read

env:
  DEPLOY_DIR: /opt/myapp/frontend
  PROJECT_NAME: frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT != '' && secrets.SSH_PORT || '22' }}
          source: |
            ./Dockerfile
            ./docker-compose.yml
            ./nginx.conf
            ./.env
          target: ${{ env.DEPLOY_DIR }}
          overwrite: true
          strip_components: 0

      - uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT != '' && secrets.SSH_PORT || '22' }}
          envs: DEPLOY_DIR,PROJECT_NAME
          script: |
            set -e
            cd "$DEPLOY_DIR"
            if [ -f "Makefile" ]; then
              make build
              make migrate
              make up
            else
              docker compose down || true
              docker compose build
              docker compose up -d

