name: Frontend CI/CD (debug)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: {}

concurrency:
  group: deploy-frontend
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  FRONTEND_IMAGE: technopolis-frontend   # имя образа фронта

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      owner_lower: ${{ steps.lower_owner.outputs.val }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # DEBUG: покажем, что реально есть в корне
      - name: Debug - list files at repo root
        run: |
          pwd
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          ls -la
          echo "---- find docker/nginx files ----"
          find . -maxdepth 2 -type f \( -name "Dockerfile" -o -name "nginx.conf" -o -name "docker-compose.yml" -o -name "compose.yml" -o -name "docker-compose.yaml" -o -name "compose.yaml" \) -print -exec ls -l {} \;

      - name: Owner -> lowercase
        id: lower_owner
        run: echo "val=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_OUTPUT"

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      # Сборка образа фронта по Dockerfile в корне репо
      - name: Build & Push frontend
        id: bp
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.lower_owner.outputs.val }}/${{ env.FRONTEND_IMAGE }}:sha-${{ github.sha }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ steps.lower_owner.outputs.val }}/${{ env.FRONTEND_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ steps.lower_owner.outputs.val }}/${{ env.FRONTEND_IMAGE }}:buildcache,mode=max

      # DEBUG: вывести дайджест и метаданные сборки
      - name: Debug - image digest & metadata
        run: |
          echo "IMAGE=${{ env.REGISTRY }}/${{ steps.lower_owner.outputs.val }}/${{ env.FRONTEND_IMAGE }}:sha-${{ github.sha }}"
          echo "DIGEST=${{ steps.bp.outputs.digest || 'n/a' }}"
          test -f "$GITHUB_OUTPUT" || true

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    env:
      OWNER_LOWER: ${{ needs.build-and-push.outputs.owner_lower }}
      FRONTEND_TAG: sha-${{ github.sha }}

    steps:
      - name: Checkout repository (for scp)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # DEBUG: убедимся, что файлы существуют именно в корне раннера
      - name: Debug - verify files exist before SCP
        run: |
          set -euxo pipefail
          pwd
          ls -la
          test -f ./docker-compose.yml && echo "OK: docker-compose.yml found" || (echo "MISS: docker-compose.yml" && exit 1)
          test -f ./nginx.conf && echo "OK: nginx.conf found" || (echo "MISS: nginx.conf" && exit 1)

      # Копируем ТОЛЬКО эти два файла из корня
      - name: Upload compose & nginx to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          source: |
            ./docker-compose.yml
            ./nginx.conf
          target: ${{ secrets.SERVER_DIR }}
          overwrite: true
          strip_components: 0
          rm: false

      # DEBUG: проверим, что файлы приехали на сервер
      - name: Remote debug - ls in SERVER_DIR
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            set -euxo pipefail
            cd "${{ secrets.SERVER_DIR }}"
            pwd
            ls -la
            sha256sum docker-compose.yml nginx.conf || true

      # Деплой фронта (nginx/фронт, БЭК НЕ ТРОГАЕМ)
      - name: Remote deploy (frontend only, with debug)
        uses: appleboy/ssh-action@v1.2.0
        env:
          SERVER_DIR:   ${{ secrets.SERVER_DIR }}
          OWNER_LOWER:  ${{ env.OWNER_LOWER }}
          FRONTEND_TAG: ${{ env.FRONTEND_TAG }}
          REGISTRY:     ${{ env.REGISTRY }}
          FRONTEND_IMAGE: ${{ env.FRONTEND_IMAGE }}
          GHCR_USER:    ${{ secrets.GHCR_READ_USERNAME || github.actor }}
          GHCR_TOKEN:   ${{ secrets.GHCR_READ_TOKEN    || secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          envs: SERVER_DIR,OWNER_LOWER,FRONTEND_TAG,REGISTRY,FRONTEND_IMAGE,GHCR_USER,GHCR_TOKEN
          script: |
            set -euxo pipefail
            cd "$SERVER_DIR"
            echo "SERVER_DIR=$(pwd)"

            # 0) Docker login + сеть на всякий
            docker login ${REGISTRY} -u "${GHCR_USER}" -p "${GHCR_TOKEN}"
            docker network create apps || true

            # 1) deploy.env: только фронтовые теги
            touch deploy.env
            sed -i '/^FRONTEND_OWNER=/d;/^FRONTEND_TAG=/d' deploy.env
            cat >> deploy.env <<EOF
            FRONTEND_OWNER=${OWNER_LOWER}
            FRONTEND_TAG=${FRONTEND_TAG}
            EOF
            echo "== deploy.env ==" && cat deploy.env

            # 2) собрать список compose-файлов
            FILES=""
            for f in docker-compose.yml compose.yml; do [ -f "$f" ] && FILES="$FILES -f $f"; done
            for f in compose.override.yml compose.db.yml; do [ -f "$f" ] && FILES="$FILES -f $f"; done
            if [ -z "$FILES" ]; then
              echo "compose-файлы не найдены в $SERVER_DIR"; exit 1
            fi
            echo "FILES=$FILES"

            compose() { docker compose $FILES --env-file .env --env-file deploy.env "$@"; }

            echo "== docker compose config --services =="
            compose config --services || true

            # 3) подтянуть новые образы (если в compose указаны image:)
            compose pull --ignore-buildable || true

            # 4) поднять front/nginx и показать их статус
            (compose up -d frontend || true)
            (compose up -d nginx || true)

            echo "== docker compose ps =="
            compose ps || true

            echo "== docker logs (last lines) =="
            (compose logs --tail=60 nginx || true)
            (compose logs --tail=60 frontend || true)

            # 5) healthcheck фронта
            set +e
            for u in http://localhost/ http://127.0.0.1/; do
              if curl -fsS "$u" >/dev/null 2>&1; then
                echo "OK: frontend is up at $u"
                exit 0
              fi
            done
            echo "Frontend healthcheck failed, dumping logs…"
            compose logs --no-color --tail=200 nginx || true
            compose logs --no-color --tail=200 frontend || true
            exit 1
